/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import Utils.FileUtils;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ernesto
 */
public class Landing extends javax.swing.JPanel {

    /**
     * Creates new form Landing
     */
    GeneratorControllerInterface gci;
    FileUtils fileUtils;
    public Landing(GeneratorControllerInterface gti) {
        this.gci = gti;
        fileUtils = new FileUtils();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        excelPanelButton = new javax.swing.JButton();
        excelPanelTextfield = new javax.swing.JTextField();
        excelPanelLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        csvPanelButton = new javax.swing.JButton();
        csvPanelTextfield = new javax.swing.JTextField();
        csvPanelLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        reportPanelButton = new javax.swing.JButton();
        reportPanelTextfield = new javax.swing.JTextField();
        reportPanelLabel = new javax.swing.JLabel();
        LandingPanelOk = new javax.swing.JButton();
        LandingPanelCancel = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setBackground(java.awt.Color.gray);
        setMaximumSize(new java.awt.Dimension(369, 367));
        setMinimumSize(new java.awt.Dimension(369, 367));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Generador de Informes");

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 70));

        excelPanelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/icons/excel2013.png"))); // NOI18N
        excelPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelPanelButtonActionPerformed(evt);
            }
        });

        excelPanelTextfield.setEditable(false);
        excelPanelTextfield.setBackground(new java.awt.Color(255, 255, 255));
        excelPanelTextfield.setColumns(20);

        excelPanelLabel.setBackground(new java.awt.Color(0, 0, 0));
        excelPanelLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        excelPanelLabel.setForeground(new java.awt.Color(0, 0, 0));
        excelPanelLabel.setText("Documento Excel con las encuestas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(excelPanelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excelPanelTextfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(excelPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(excelPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excelPanelTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(excelPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(java.awt.Color.lightGray);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(325, 70));

        csvPanelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/icons/iconoCsv.png"))); // NOI18N
        csvPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvPanelButtonActionPerformed(evt);
            }
        });

        csvPanelTextfield.setEditable(false);
        csvPanelTextfield.setBackground(new java.awt.Color(255, 255, 255));
        csvPanelTextfield.setColumns(20);

        csvPanelLabel.setBackground(new java.awt.Color(0, 0, 0));
        csvPanelLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        csvPanelLabel.setForeground(new java.awt.Color(0, 0, 0));
        csvPanelLabel.setText("CSV de los estudios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(csvPanelLabel)
                    .addComponent(csvPanelTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(csvPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(csvPanelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(csvPanelTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(csvPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(java.awt.Color.lightGray);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        reportPanelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/icons/wordDestino.png"))); // NOI18N
        reportPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportPanelButtonActionPerformed(evt);
            }
        });

        reportPanelTextfield.setEditable(false);
        reportPanelTextfield.setBackground(new java.awt.Color(255, 255, 255));
        reportPanelTextfield.setColumns(20);

        reportPanelLabel.setBackground(new java.awt.Color(0, 0, 0));
        reportPanelLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        reportPanelLabel.setForeground(new java.awt.Color(0, 0, 0));
        reportPanelLabel.setText("Destino de los informes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportPanelLabel)
                    .addComponent(reportPanelTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reportPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reportPanelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reportPanelTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(reportPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        LandingPanelOk.setBackground(new java.awt.Color(51, 102, 255));
        LandingPanelOk.setForeground(new java.awt.Color(255, 255, 255));
        LandingPanelOk.setText("Comenzar");
        LandingPanelOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LandingPanelOkActionPerformed(evt);
            }
        });

        LandingPanelCancel.setBackground(new java.awt.Color(195, 68, 50));
        LandingPanelCancel.setForeground(new java.awt.Color(255, 255, 255));
        LandingPanelCancel.setText("Cancelar");
        LandingPanelCancel.setMaximumSize(new java.awt.Dimension(88, 31));
        LandingPanelCancel.setMinimumSize(new java.awt.Dimension(88, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LandingPanelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LandingPanelOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LandingPanelCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(LandingPanelOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTextExcelPanelTextfield(String text){
        excelPanelTextfield.setText(text);
    }
    
    private void LandingPanelOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LandingPanelOkActionPerformed

        JPanel cards = (JPanel) getParent();
        CardLayout cl = (CardLayout)(cards.getLayout());
        cl.next(cards);
        gci.loadExcelTable(gci.getExcelPath());
    }//GEN-LAST:event_LandingPanelOkActionPerformed

    private void excelPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelPanelButtonActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        String[] filePathAndName = fileUtils.getFilePathAndName(fileChooser, new String[] {"xls", "xlsx"});
        gci.setExcelPath(filePathAndName[0]);
        gci.setTextTextfield(excelPanelTextfield, filePathAndName[1]);
    }//GEN-LAST:event_excelPanelButtonActionPerformed

    private void csvPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvPanelButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        String[] filePathAndName = fileUtils.getFilePathAndName(fileChooser, new String[] {"csv"});
        gci.setCsvPath(filePathAndName[0]);
        gci.setTextTextfield(csvPanelTextfield, filePathAndName[1]);
    }//GEN-LAST:event_csvPanelButtonActionPerformed

    private void reportPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportPanelButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        String[] filePathAndName = fileUtils.getFilePathAndName(fileChooser, null);
        gci.setReportPath(filePathAndName[0]);
        gci.setTextTextfield(reportPanelTextfield, filePathAndName[1]);
    }//GEN-LAST:event_reportPanelButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LandingPanelCancel;
    private javax.swing.JButton LandingPanelOk;
    private javax.swing.JButton csvPanelButton;
    private javax.swing.JLabel csvPanelLabel;
    private javax.swing.JTextField csvPanelTextfield;
    private javax.swing.JButton excelPanelButton;
    private javax.swing.JLabel excelPanelLabel;
    private javax.swing.JTextField excelPanelTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton reportPanelButton;
    private javax.swing.JLabel reportPanelLabel;
    private javax.swing.JTextField reportPanelTextfield;
    // End of variables declaration//GEN-END:variables
}
