/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import Panels.Questions;
import java.awt.BorderLayout;
import javax.swing.JButton;

/**
 *
 * @author ernesto
 */
public class Wizard extends javax.swing.JPanel {

    /**
     * Creates new form Wizard
     */
    private GeneratorControllerInterface gci;
    static Questions numericas;
    static Questions texto;
    
    public Wizard(){};
    
    public Wizard(GeneratorControllerInterface gci) {
        this.gci = gci;
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        TabbedPane = new javax.swing.JTabbedPane();
        wizard_tab1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Tab1_next = new javax.swing.JButton();
        Tab1_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        wizard_tab1Panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        Tab2_next = new javax.swing.JButton();
        Tab2_cancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        wizard_tab2Panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Tab3_next = new javax.swing.JButton();
        Tab3_cancel = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jTextField1.setText("jTextField1");

        wizard_tab1.setName(""); // NOI18N

        Tab1_next.setText("next");
        Tab1_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab1_nextActionPerformed(evt);
            }
        });

        Tab1_cancel.setText("cancel");
        Tab1_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab1_cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Preguntas númericas:");

        javax.swing.GroupLayout wizard_tab1PanelLayout = new javax.swing.GroupLayout(wizard_tab1Panel);
        wizard_tab1Panel.setLayout(wizard_tab1PanelLayout);
        wizard_tab1PanelLayout.setHorizontalGroup(
            wizard_tab1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        wizard_tab1PanelLayout.setVerticalGroup(
            wizard_tab1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout wizard_tab1Layout = new javax.swing.GroupLayout(wizard_tab1);
        wizard_tab1.setLayout(wizard_tab1Layout);
        wizard_tab1Layout.setHorizontalGroup(
            wizard_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizard_tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wizard_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wizard_tab1Layout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addComponent(Tab1_cancel)
                        .addGap(27, 27, 27)
                        .addComponent(Tab1_next))
                    .addGroup(wizard_tab1Layout.createSequentialGroup()
                        .addGroup(wizard_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wizard_tab1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        wizard_tab1Layout.setVerticalGroup(
            wizard_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizard_tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wizard_tab1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wizard_tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tab1_next)
                    .addComponent(Tab1_cancel)))
        );

        TabbedPane.addTab("tab1", wizard_tab1);

        Tab2_next.setText("next");
        Tab2_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab2_nextActionPerformed(evt);
            }
        });

        Tab2_cancel.setText("cancel");
        Tab2_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab2_cancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Preguntas de texto");

        javax.swing.GroupLayout wizard_tab2PanelLayout = new javax.swing.GroupLayout(wizard_tab2Panel);
        wizard_tab2Panel.setLayout(wizard_tab2PanelLayout);
        wizard_tab2PanelLayout.setHorizontalGroup(
            wizard_tab2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        wizard_tab2PanelLayout.setVerticalGroup(
            wizard_tab2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(290, Short.MAX_VALUE)
                        .addComponent(Tab2_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tab2_next))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(wizard_tab2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wizard_tab2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tab2_next)
                    .addComponent(Tab2_cancel))
                .addContainerGap())
        );

        TabbedPane.addTab("tab2", jPanel2);

        jLabel3.setText("jLabel3");

        Tab3_next.setText("next");
        Tab3_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab3_nextActionPerformed(evt);
            }
        });

        Tab3_cancel.setText("cancel");
        Tab3_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab3_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addComponent(Tab3_cancel)
                        .addGap(27, 27, 27)
                        .addComponent(Tab3_next)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tab3_next)
                    .addComponent(Tab3_cancel))
                .addContainerGap())
        );

        TabbedPane.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void Tab1_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab1_cancelActionPerformed
        // TODO add your handling code here:
       gci.previousButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab1_cancelActionPerformed

    private void Tab3_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab3_nextActionPerformed
        // TODO add your handling code here:
        gci.nextButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab3_nextActionPerformed

    private void Tab3_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab3_cancelActionPerformed
        // TODO add your handling code here:
        gci.previousButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab3_cancelActionPerformed

    private void Tab1_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab1_nextActionPerformed
        // TODO add your handling code here:
        gci.nextButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab1_nextActionPerformed

    private void Tab2_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab2_cancelActionPerformed
        // TODO add your handling code here:
        gci.previousButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab2_cancelActionPerformed

    private void Tab2_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab2_nextActionPerformed
        // TODO add your handling code here:

        gci.nextButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab2_nextActionPerformed
    
    
    
    private void myInit(){
        System.out.println("inicio del wizzard");
        numericas   = new Questions(gci);
        texto   = new Questions(gci);
//        numericas.loadExcel(gci.getExcelPath());
        wizard_tab1Panel.setLayout(new BorderLayout());
        wizard_tab1Panel.add(numericas,BorderLayout.NORTH); 
        wizard_tab2Panel.setLayout(new BorderLayout());
        wizard_tab2Panel.add(texto,BorderLayout.NORTH); 
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tab1_cancel;
    private javax.swing.JButton Tab1_next;
    private javax.swing.JButton Tab2_cancel;
    private javax.swing.JButton Tab2_next;
    private javax.swing.JButton Tab3_cancel;
    private javax.swing.JButton Tab3_next;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel wizard_tab1;
    private javax.swing.JPanel wizard_tab1Panel;
    private javax.swing.JPanel wizard_tab2Panel;
    // End of variables declaration//GEN-END:variables
}
