/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import Panels.Numericas;
import javax.swing.JButton;

/**
 *
 * @author ernesto
 */
public class Wizard extends javax.swing.JPanel {

    /**
     * Creates new form Wizard
     */
    GeneratorControllerInterface gti;
    
    public Wizard(){};
    
    public Wizard(GeneratorControllerInterface gti) {
        this.gti = gti;
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        TabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Tab1_next = new javax.swing.JButton();
        Tab1_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Tab2_next = new javax.swing.JButton();
        Tab2_cancel = new javax.swing.JButton();
        txfield2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Tab3_next = new javax.swing.JButton();
        Tab3_cancel = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jTextField1.setText("jTextField1");

        Tab1_next.setText("next");
        Tab1_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab1_nextActionPerformed(evt);
            }
        });

        Tab1_cancel.setText("cancel");
        Tab1_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab1_cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Preguntas númericas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addComponent(Tab1_cancel)
                        .addGap(27, 27, 27)
                        .addComponent(Tab1_next))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tab1_next)
                    .addComponent(Tab1_cancel)))
        );

        TabbedPane.addTab("tab1", jPanel1);

        jLabel2.setText("jLabel2");

        Tab2_next.setText("next");
        Tab2_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab2_nextActionPerformed(evt);
            }
        });

        Tab2_cancel.setText("cancel");
        Tab2_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab2_cancelActionPerformed(evt);
            }
        });

        txfield2.setText("jTextField2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addComponent(txfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tab2_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tab2_next)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tab2_next)
                    .addComponent(Tab2_cancel))
                .addContainerGap())
        );

        TabbedPane.addTab("tab2", jPanel2);

        jLabel3.setText("jLabel3");

        Tab3_next.setText("next");
        Tab3_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab3_nextActionPerformed(evt);
            }
        });

        Tab3_cancel.setText("cancel");
        Tab3_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab3_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addComponent(Tab3_cancel)
                        .addGap(27, 27, 27)
                        .addComponent(Tab3_next)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tab3_next)
                    .addComponent(Tab3_cancel))
                .addContainerGap())
        );

        TabbedPane.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void Tab1_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab1_cancelActionPerformed
        // TODO add your handling code here:
       gti.previousButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab1_cancelActionPerformed

    private void Tab2_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab2_nextActionPerformed
        // TODO add your handling code here:
        int n = Integer.parseInt(getTextField2());
        gti.nextButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab2_nextActionPerformed

    private void Tab2_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab2_cancelActionPerformed
        // TODO add your handling code here:
        gti.previousButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab2_cancelActionPerformed

    private void Tab3_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab3_nextActionPerformed
        // TODO add your handling code here:
        gti.nextButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab3_nextActionPerformed

    private void Tab3_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab3_cancelActionPerformed
        // TODO add your handling code here:
        gti.previousButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab3_cancelActionPerformed

    private void Tab1_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab1_nextActionPerformed
        // TODO add your handling code here:
        gti.nextButton((JButton) evt.getSource(), TabbedPane);
    }//GEN-LAST:event_Tab1_nextActionPerformed
    
    private String getTextField2(){
        return txfield2.getText();
    };
    
    private void myInit(){
        System.out.println("inicio del wizzard");
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tab1_cancel;
    private javax.swing.JButton Tab1_next;
    public javax.swing.JButton Tab2_cancel;
    private javax.swing.JButton Tab2_next;
    private javax.swing.JButton Tab3_cancel;
    private javax.swing.JButton Tab3_next;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txfield2;
    // End of variables declaration//GEN-END:variables
}
